quotes = [
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "Life can only be understood backwards; but it must be lived forwards.",
    "Memory is the diary we all carry about with us.",
    "Sometimes you will never know the value of a moment until it becomes a memory.",
    "Books are a uniquely portable magic.",
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Two roads diverged in a wood, and I took the one less traveled by.",
    "Be the change you wish to see in the world.",
    "Every moment is a fresh beginning.",
    "The only impossible journey is the one you never begin.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Everything you can imagine is real.",
    "Change your thoughts and you change your world.",
    "The purpose of our lives is to be happy.",
    "Yesterday is not ours to recover, but tomorrow is ours to win or lose.",
    "The best way to predict the future is to create it.",
    "A room without books is like a body without a soul.",
    "Education is not preparation for life; education is life itself.",
    "Time is the most valuable thing a man can spend.",
    "The journey of a thousand miles begins with one step.",
    "Everything has beauty, but not everyone sees it.",
    "We write to taste life twice, in the moment and in retrospect.",
    "Happiness is not something ready made. It comes from your own actions.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Love all, trust a few, do wrong to none.",
    "It is never too late to be what you might have been.",
    "Life is either a daring adventure or nothing at all.",
    "The only true wisdom is in knowing you know nothing.",
    "The secret of getting ahead is getting started.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The unexamined life is not worth living.",
    "Time you enjoy wasting is not wasted time.",
    "Knowledge speaks, but wisdom listens.",
    "Life is really simple, but we insist on making it complicated.",
    "The mind is everything. What you think you become.",
    "Not all those who wander are lost.",
    "Imagination is more important than knowledge.",
    "Do what you can, with what you have, where you are.",
    "The more I learn, the more I realize how much I don't know.",
    "Success is falling nine times and getting up ten.",
    "The past is never dead. It's not even past.",
    "You must be the change you wish to see in the world.",
    "If you want to lift yourself up, lift up someone else.",
    "Life shrinks or expands in proportion to one's courage.",
    "A ship in harbor is safe, but that is not what ships are built for.",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "The beautiful thing about learning is that no one can take it away from you.",
    "Life is a succession of lessons which must be lived to be understood."
]