quotes = [
  "The key is not to prioritize what's on your schedule, but to schedule your priorities.",
  "Focus on being productive instead of busy.",
  "Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.",
  "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.",
  "Focus does not mean saying yes, it means saying no.",
  "If you want to be happy, do not dwell in the past, do not worry about the future, focus on living fully in the present.",
  "Failure isn't fatal, but failure to change might be.",
  "Everything you want is on the other side of fear.",
  "The secret of life is to fall seven times and to get up eight times.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Let the improvement of yourself keep you so busy that you have no time to criticize others.",
  "Always work hard and have fun in what you do because I think that's when you're more successful. You have to choose to do it.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "It's not about having enough time, it's about making enough time.",
  "The only place where success comes before work is in the dictionary.",
  "Don't be afraid to give up the good to go for the great.",
  "Discipline is the bridge between goals and accomplishment.",
  "The more you eliminate the inefficient use of information, energy, and time, the more productive you become.",
  "You don't have to see the whole staircase, just take the first step.",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
  "You miss 100% of the shots you don't take.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "There are no shortcuts to any place worth going.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "The successful warrior is the average man, with laser-like focus.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
  "The way to get started is to quit talking and begin doing.",
  "Either you run the day or the day runs you.",
  "Start where you are. Use what you have. Do what you can.",
  "The difference between ordinary and extraordinary is that little extra.",
  "The question isn't who is going to let me; it's who is going to stop me.",
  "Don't count the days, make the days count.",
  "Quality is not an act, it is a habit.",
  "The question isn't whether you'll meet obstacles. The question is whether you'll let them stop you.",
  "It always seems impossible until it's done.",
  "The path to success is to take massive, determined action.",
  "If you're going through hell, keep going.",
  "The only way to do great work is to love what you do.",
  "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.",
  "You become what you believe.",
  "The best way to predict the future is to create it.",
  "Believe you can and you're halfway there.",
  "Your time is limited, don't waste it living someone else's life.",
  "Success is not how high you have climbed, but how you make a positive difference to the world."
]